// https://miro.com/app/?copyBoardId=uXjVKTtrd2w=&isMiroverseTemplate=true
// https://miro.com/app/?copyBoardId=uXjVKTtrd2w%3D&copyTemplateMetaId=5cd000ad-c3e8-45de-aa66-d347ef1e0c2a&isMiroverseTemplate=true

export const MIRO_TEMPLATES = [
  {
    id: "uXjVKTtrd2w=",
    title: "Gratitude Journal",
    url: "https://miro.pxf.io/1r4gxD",
    description: "Start giving thanks and keeping a gratitude journal in Miro.",
    tags: [
      "Gratitude",
      "daily",
      "mindfulness",
      "journal",
      "exercise",
      "personal",
      "reflection",
      "journaling",
      "health",
      "mental",
      "practice",
      "well-being",
      "wellbeing",
      "digital",
      "doodle",
      "doodles",
      "emotional",
      "emotions",
      "printable",
      "print",
      "paper",
    ],
  },
  {
    id: "uXjVKOwaHhU=",
    title: "A Hive-ly Retrospective!",
    url: "https://miro.pxf.io/B04GqL",
    description:
      "Commemorate World Bee Day with this retrospective board, adorned with bee-themed decorations serving as a hive of reflection.",
    tags: [
      "Hively",
      "Hive",
      "retrospective",
      "bee-theme",
      "bee",
      "team",
      "reflection",
      "agile",
      "success",
      "failure",
      "sharing",
      "lesson",
      "notes",
      "post-it",
      "moments",
      "buzzkill",
      "collaboration",
      "innovation",
      "World Bee Day",
      "achievements",
      "team",
      "future",
      "planning",
      "workflows",
      "workshops",
      "digital",
      "exercise",
    ],
  },
  {
    id: "uXjVKOxk2Ak=",
    title: "Star Wars Puzzle Time",
    url: "https://miro.pxf.io/NkrKMN",
    description:
      "Embark on an epic journey through the galaxy with these Star Wars-themed jigsaw puzzles! 4 puzzles to mark the fourth! ",
    tags: [
      "Puzzle",
      "Star",
      "Wars",
      "Puzzle",
      "jigsaw",
      "galaxy",
      "movie",
      "poster",
      "characters",
      "adventure",
      "Fourth",
      "May",
      "challenge",
      "fun",
      "theme",
      "journey",
      "interactive",
      "team",
      "building",
      "icebreaker",
      "game",
      "digital",
      "saga",
    ],
  },
  {
    id: "o9J_lHSC6A0=",
    title: "The 4-Step Retrospective",
    url: "https://miro.pxf.io/PyP0Mq",
    description:
      "The 4-step retrospective board is intended to quickly add a simple retrospective template for your retro sessions. ",
    tags: [
      "4",
      "four",
      "4-Step",
      "simple",
      "step",
      "team",
      "reflection",
      "retrospective",
      "agile",
      "sprint",
      "review",
      "collaboration",
      "appreciate",
      "well",
      "better",
      "actions",
      "improvements",
      "planning",
      "feedback",
      "simple",
      "achievements",
      "celebrate",
      "actionable",
      "actions",
      "tasks",
      "workshops",
      "success",
      "failure",
    ],
  },
  {
    id: "uXjVKVRJS1w=",
    title: "Circular Conundrums: Easy Maze Marvels",
    url: "https://miro.pxf.io/q47naq",
    description:
      "Side step into the land of Maze Marvels but only this time, we're dealing with circular mazes in Miro.",
    tags: [
      "Conundrums",
      "Easy",
      "Maze",
      "Marvels",
      "circular",
      "challenge",
      "activity",
      "team",
      "interactive",
      "pen",
      "building",
      "fun",
      "collaboration",
      "problem-solving",
      "problem",
      "adventure",
      "game",
      "navigation",
      "exercise",
      "group",
      "activity",
    ],
  },
  {
    id: "uXjVKVWEo3w=",
    title: "Hexa-Maze Magic: Easy Maze Escapades",
    url: "https://miro.pxf.io/Qy5OM9",
    description:
      "Side step into the land of Maze Marvels but only this time, we're dealing with hexagonal mazes in Miro.",
    tags: [
      "Hexa-Maze",
      "Magic",
      "Escapades",
      "Easy",
      "Maze",
      "Marvels",
      "circular",
      "challenge",
      "activity",
      "team",
      "interactive",
      "pen",
      "building",
      "fun",
      "collaboration",
      "problem-solving",
      "problem",
      "adventure",
      "game",
      "navigation",
      "exercise",
      "group",
      "activity",
    ],
  },
  {
    id: "uXjVKWQkBQY=",
    title: "Maze Marvels: Navigate the Challenge!",
    url: "https://miro.pxf.io/ZQZdM0",
    description:
      "The next step of Maze Marvels — Navigate the Challenge — is slightly intermediate-level maze puzzles.",
    tags: [
      "Navigate",
      "intermediate",
      "Easy",
      "Maze",
      "Marvels",
      "circular",
      "challenge",
      "activity",
      "team",
      "interactive",
      "pen",
      "building",
      "fun",
      "collaboration",
      "problem-solving",
      "problem",
      "adventure",
      "game",
      "navigation",
      "exercise",
      "group",
      "activity",
    ],
  },
  {
    id: "uXjVKWQUzKI=",
    title: "Maze Marvels: Dare to Navigate the Depths!",
    url: "https://miro.pxf.io/0ZeJVY",
    description:
      "The next step of Maze Marvels — Dare to Navigate the Depths — is hard-level maze puzzles.",
    tags: [
      "Navigate",
      "hard",
      "intermediate",
      "Easy",
      "Maze",
      "Marvels",
      "circular",
      "challenge",
      "activity",
      "team",
      "interactive",
      "pen",
      "building",
      "fun",
      "collaboration",
      "problem-solving",
      "problem",
      "adventure",
      "game",
      "navigation",
      "online maze",
      "exercise",
      "group",
      "activity",
    ],
  },
  {
    id: "uXjVKWQriEQ=",
    title: "Maze Marvels: Fun and Simple Paths to Solve!",
    url: "https://miro.pxf.io/eK64L6",
    description:
      "This is the first of Maze Marvels — an easy introduction to maze puzzles on Miro",
    tags: [
      "Simple",
      "Navigate",
      "hard",
      "intermediate",
      "Easy",
      "Maze",
      "Marvels",
      "circular",
      "challenge",
      "activity",
      "team",
      "interactive",
      "pen",
      "building",
      "fun",
      "collaboration",
      "problem-solving",
      "problem",
      "adventure",
      "game",
      "navigation",
      "online maze",
      "exercise",
      "group",
      "activity",
    ],
  },
  {
    id: "uXjVKXpy5ok=",
    title: "The Achievable Mountain",
    url: "https://miro.pxf.io/Mm9X7Y",
    description:
      "Visualize your goals in three categories — safe and achievable, ambitious but achievable, and ambitious and far-fetched — to help you pinpoint where to direct your focus.",
    tags: [
      "Achieve",
      "Mountain",
      "setting",
      "goal",
      "goals",
      "visualize",
      "safe",
      "ambitious",
      "far-fetched",
      "categories",
      "focus",
      "direction",
      "motivational",
      "development",
      "personal",
      "planning",
      "visualization",
      "success",
      "team",
      "productivity",
      "tracking",
      "strategy",
      "achievement",
    ],
  },
  {
    id: "uXjVKZRh5Ks=",
    title: "International Museum Day",
    url: "https://miro.pxf.io/m57gYy",
    description:
      "This International Museum Day, run a fun icebreaker activity in this virtual museum! Enter the museum and open the inside door, as marked, to reveal the icebreaker question.",
    tags: [
      "Museum",
      "International",
      "virtual",
      "activity",
      "icebreaker",
      "participation",
      "team",
      "museum-themed",
      "building",
      "interactive",
      "group",
      "exercise",
      "event",
      "engagement",
      "creative",
      "exhibit",
      "exhibition",
      "science",
      "fair",
    ],
  },
  {
    id: "uXjVNrjt7Vo=",
    title: "Easter Egg Prompts",
    url: "https://miro.pxf.io/GmvVA9",
    description:
      "Easter eggs are falling Answer the prompts behind the eggs Before the Easter Bunny gets it all in the basket.",
    tags: [
      "Egg",
      "Easter",
      "Prompts",
      "jesus",
      "Easter-themed",
      "icebreaker",
      "game",
      "team",
      "interactive",
      "eggs",
      "virtual",
      "activity",
      "engagement",
      "fun",
      "exercise",
      "group",
      "bunny",
      "collaboration",
      "creative",
      "basket",
    ],
  },
  {
    id: "uXjVNni08_U=",
    title: "Earth Day: Where Do I Go?",
    url: "https://miro.pxf.io/xk750R",
    description:
      "Let's come together to make a positive impact by playing Where Do I Go? In this engaging game, participants collaborate to segregate online images of various types of rubbish into colorful virtual bins.",
    tags: [
      "Earth",
      "Day",
      "eco-friendly",
      "ecofriendly",
      "activity",
      "game",
      "waste",
      "management",
      "recycling",
      "awareness",
      "icebreaker",
      "virtual",
      "team",
      "environmental",
      "interactive",
      "engagement",
      "sustainability",
      "celebration",
      "green",
      "planet",
      "segregation",
      "eco-conscious",
      "group",
    ],
  },
  {
    id: "uXjVNr8oVgE=",
    title: "Eco-Friendly Meter",
    url: "https://miro.pxf.io/jrvyM6",
    description:
      "In this Earth Day-based activity, let's find out how eco-friendly of a team you are. 🌍",
    tags: [
      "Eco-Friendly",
      "EcoFriendly",
      "activity",
      "team",
      "engagement",
      "awareness",
      "environmental",
      "sticky",
      "collaboration",
      "green",
      "eco-conscious",
      "ecoconscious",
      "virtual",
      "interactive",
      "sustainability",
      "impact",
      "goals",
      "game",
      "exercise",
    ],
  },
  {
    id: "uXjVNplaIYs=",
    title: "Color Me Green and Blue",
    url: "https://miro.pxf.io/k0mM73",
    description:
      "This Earth Day, let's celebrate the beauty of our planet by collectively adding a burst of color to it! Imagine covering the Earth with vibrant green and blue sticky notes, each carrying a positive and uplifting message for the future.",
    tags: [
      "Color",
      "Colour",
      "Coloring",
      "Colouring",
      "Blue",
      "Green",
      "Earth",
      "activity",
      "team",
      "engagement",
      "environmental",
      "awareness",
      "interactive",
      "positive",
      "positivity",
      "messages",
      "nature",
      "reflection",
      "activity",
      "virtual",
      "sustainability",
      "collaboration",
      "celebration",
      "exercise",
      "hopeful",
      "protection",
      "chalk",
      "planet",
    ],
  },
  {
    id: "uXjVNrsfXbQ=",
    title: "Know Your Trees",
    url: "https://miro.pxf.io/eK6EOQ",
    description:
      "There are about 73,300 species of trees on Earth — and each plays an important role in helping humanity thrive. Let's play a game to get to know our trees more.",
    tags: [
      "Trees",
      "tree",
      "identification",
      "conservation",
      "nature",
      "interactive",
      "learning",
      "species",
      "environmental",
      "education",
      "activity",
      "guessing",
      "connect",
      "dots",
      "biodiversity",
      "forest",
      "group",
      "ecology",
      "awareness",
      "knowledge",
    ],
  },
  {
    id: "uXjVN-Ly_bs=",
    title: "Riddle Me This",
    url: "https://miro.pxf.io/LXQ4ao",
    description:
      "This Miro board comes with a bunch of riddles to keep your mind busy. As a facilitator, you can use this board as an icebreaker activity with any type of meeting or even just as a standalone activity.",
    tags: [
      "Riddle",
      "Riddles",
      "sherlock",
      "game",
      "icebreaker",
      "team",
      "interactive",
      "engagement",
      "brain",
      "brain-teaser",
      "fun",
      "group",
      "challenge",
      "mind",
      "puzzle",
      "exercise",
      "creative",
      "problem-solving",
      "collaboration",
    ],
  },
  {
    id: "uXjVNBp_G8o=",
    title: "Mirocooked Icebreaker",
    url: "https://miro.pxf.io/EK3J0P",
    // https://miro.com/miroverse/mirocooked-icebreaker-template/
    description:
      "Your challenge for today is to help these two chefs in the kitchen and put together a delicious pizza for our guests. ",
    tags: [
      "Mirocooked",
      "Icebreaker",
      "cook",
      "masterchef",
      "pizza",
      "byo",
      "kitchen",
      "activity",
      "team",
      "building",
      "overcooked",
    ],
  },
  {
    id: "o9J_lqtgU9c=",
    title: "Bulls Eye Feedback",
    url: "https://miro.pxf.io/9gXOVW",
    // https://miro.com/miroverse/bulls-eye-feedback/
    description:
      "Include Bulls Eye Feedback in any of your existing workshop Miro boards to get your team's feedback on your workshop by asking them to place one of the custom made darts anywhere in the target.",
    tags: [
      "Bulls",
      "Eye",
      "Feedback",
      "bull",
      "target",
      "dart",
      "arrow",
      "bow",
      "aim",
    ],
  },
  {
    id: "uXjVNENHsLg=",
    title: "What's Your Cupid Name?",
    url: "https://miro.pxf.io/21AMRz",
    // https://miro.com/miroverse/whats-your-cupid-name-template/
    description:
      "In this Valentine's Day-themed icebreaker, get your participants to create their cupid name. You do this by combining a sweet adjective corresponding to the first letter of your name with a cute romantic nickname corresponding to the month you were born.",
    tags: [
      "Cupid",
      "name",
      "guess",
      "icebreaker",
      "game",
      "virtual",
      "activity",
      "team",
      "building",
      "valentine",
      "feb",
      "february",
      "14",
    ],
  },
  {
    id: "uXjVPNKBYEU=",
    title: "A Halloween Retro",
    url: "https://miro.pxf.io/DK2Vvq",
    description:
      "October is Halloween month and if you're hosting a retrospective during this time, how can you even resist a Halloween-themed retro board?",
    tags: [
      "Halloween",
      "Halloween-themed",
      "retro",
      "reflection",
      "retrospective",
      "agile",
      "bingo",
      "review",
      "sprint",
      "collaboration",
      "spooky",
      "achievements",
      "activities",
      "feedback",
      "planning",
      "icebreaker",
      "pumpkin",
      "fun",
      "october",
    ],
  },
  {
    id: "uXjVNEKNxnE=",
    title: "Cupid Swipe Retro",
    url: "https://miro.pxf.io/y279ZV",
    //https://miro.com/miroverse/cupid-swipe-retro-template/
    description:
      "This Valentine's Day, indulge in a dating app-themed retrospective board. 💖",
    tags: [
      "Cupid",
      "valentine",
      "date",
      "dating",
      "feb",
      "february",
      "14",
      "retrospective",
      "agile",
      "scrum",
      "app",
      "retro",
    ],
  },
  {
    id: "uXjVNGV8jhE=",
    title: "Love It or Hate It? Cupid Swipe Icebreaker",
    url: "https://miro.pxf.io/9gXOeW",
    // https://miro.com/miroverse/love-hate-cupid-swipe-icebreaker-template/
    description:
      "A dating app-style icebreaker to get to know what your participants like and dislike and to get the conversations started. Use this in February as a Valentine's Day icebreaker or just any other time of the year for some giggles. ",
    tags: [
      "Cupid",
      "valentine",
      "date",
      "dating",
      "feb",
      "february",
      "14",
      "retrospective",
      "agile",
      "scrum",
      "app",
      "retro",
      "love",
      "hate",
      "swipe",
    ],
  },
  {
    id: "uXjVNE24j1g=",
    title: "A Sense of Appreciation",
    url: "https://miro.pxf.io/m57Z4e",
    // https://miro.com/miroverse/sense-of-appreciation-template/
    description:
      "With the help of some Japanese concepts, let's learn to appreciate the different aspects of life in this self-reflection board.",
    tags: [
      "Appreciation",
      "Japanese",
      "Japan",
      "appreciate",
      "self-reflection",
      "reflection",
      "sense",
    ],
  },
  {
    id: "uXjVNIeY7hc=",
    title: "Lean Coffee Cafe",
    url: "https://miro.pxf.io/VmGB4A",
    //https://miro.com/miroverse/lean-coffee-cafe-template/
    description:
      "Welcome to the Lean Coffee Cafe! Today, we have a caffeine-infused three-course menu — we start with items to discuss, then we'll proceed to items we're currently discussing, and finally, items that we've discussed. ☕",
    tags: [
      "Coffee",
      "lean",
      "cafe",
      "caffeine",
      "three",
      "course",
      "menu",
      "mocha",
      "latte",
      "café",
    ],
  },
  {
    id: "uXjVO4yVWAI=",
    title: "Space Bingo",
    url: "https://miro.pxf.io/an02Ro",
    description:
      "Enjoy a game of Space Bingo as an icebreaker for your next workshop. ",
    tags: [
      "Bingo",
      "Space",
      "icebreaker",
      "team",
      "space-themed",
      "interactive",
      "dice",
      "engagement",
      "icebreaker",
      "fun",
      "group",
      "exercise",
      "workshop",
      "creative",
      "collaboration",
      "game",
    ],
  },
  {
    id: "uXjVPaTpglg=",
    title: "Gather Town Retrospective",
    url: "https://miro.pxf.io/DK2n0a",
    description:
      "Gather Town tries to make virtual interactions more human by providing a digital space where user avatars can walk around and seamlessly interact with other humans.",
    tags: [
      "Town",
      "Gather",
      "reflection",
      "retrospective",
      "retro",
      "avatar",
      "icebreaker",
      "team",
      "well",
      "post-it",
      "kudos",
      "improvements",
      "action",
      "sprint",
      "planning",
      "unwind",
      "digital",
      "collaboration",
      "agile",
      "workflows",
      "interactive",
      "exercise",
      "human",
    ],
  },
  {
    id: "uXjVNHSP1OQ=",
    title: "Frosty Firestarter's",
    url: "https://miro.pxf.io/ZQZBrq",
    // https://miro.com/miroverse/frosty-firestarters/
    description:
      "Thanks for cloning this Frosty Firestarter's template. This is a simple icebreaker template which contains heaps of dragon-themed prompt cards in the center of the deck. 🐉",
    tags: [
      "Frosty",
      "Firestarter's",
      "Firestarter",
      "fire",
      "dragon",
      "prompt",
      "icebreaker",
      "game",
      "activity",
      "cards",
    ],
  },
  {
    id: "uXjVNJA2FJo=",
    title: "Hang Those Christmas Stockings",
    url: "https://miro.pxf.io/oq70nb",
    //https://miro.com/miroverse/hang-those-christmas-stockings-template/
    description:
      "Let's keep the Christmas stocking tradition alive virtually using this simple Miro board. Wondering how? Follow along! 🎄🎅🧦",
    tags: [
      "Hang",
      "Christmas",
      "Stocking",
      "xmas",
      "stocking",
      "sock",
      "socks",
      "santa",
      "game",
      "activity",
      "tradition",
    ],
  },
  {
    id: "o9J_lCs6DkM=",
    title: "Retrospective in the Island of Golocans",
    url: "https://miro.pxf.io/xk1NMk",
    // https://miro.com/miroverse/retrospective-in-the-island-of-golocans/
    description:
      "When performing a retrospective on the Island of Golocans, remember to cover all four directions. Have a pleasant time exploring this island!",
    tags: [
      "Retrospective",
      "retro",
      "Golocans",
      "Island",
      "featured",
      "winning",
      "award",
      "one",
      "piece",
      "strawberry",
      "gold",
      "pirate",
      "bottle",
      "explore",
      "exploration",
    ],
  },
  {
    id: "uXjVNS0uLGQ=",
    title: "Would You Rather? Shopping Edition",
    url: "https://miro.pxf.io/q47Z4j",
    // https://miro.com/miroverse/would-you-rather-shopping-edition-template/
    description:
      "To play a game of 'Would You Rather,' gather a group of participants and take turns presenting each other with a choice between two hypothetical options, often amusing, creating interesting dilemmas. Participants must choose a side using and might also go about explaining their choice if they'd like.",
    tags: [
      "Shopping",
      "Edition",
      "shop",
      "black",
      "friday",
      "nov",
      "november",
      "game",
      "icebreaker",
      "amusing",
      "creative",
      "interesting",
      "dilemma",
    ],
  },
  {
    id: "uXjVNTaX6tw=",
    title: "Black Friday Bingo Cards",
    url: "https://miro.pxf.io/zN7rxe",
    //https://miro.com/miroverse/black-friday-bingo-cards-template/
    description:
      "To play, choose a bingo card set and then ask each other if you've ever had these shopping experiences. Each person gets a card from the selected set. If you have had the shopping experience, mark the square with the marker provided.",
    tags: [
      "Black",
      "Friday",
      "Bingo",
      "Card",
      "nov",
      "november",
      "game",
      "icebreaker",
      "amusing",
    ],
  },
  {
    id: "o9J_l9J6AHY=",
    title: "The Writing Process",
    url: "https://miro.pxf.io/rQ7OQ5",
    // https://miro.com/miroverse/the-writing-process/
    description:
      "The writing process can be overwhelming at times. But it doesn't always have to be. To make your life smooth, I've created this all-in-one template that you can copy and fill up.",
    tags: ["Writing", "process", "write"],
  },
  {
    id: "uXjVNSuta38=",
    title: "Word Search Shopping Edition",
    url: "https://miro.pxf.io/rQ7On5",
    // https://miro.com/miroverse/word-search-shopping-edition-template/
    description:
      "Locate below listed words hidden within this grid of letters. These words can be arranged horizontally, vertically, or diagonally, in any direction.",
    tags: ["Word Search Shopping Edition"],
  },
  {
    id: "uXjVNT6LVfA=",
    title: "No Regrets Calendar 2024",
    url: "https://miro.pxf.io/EK3JEe",
    //https://miro.com/miroverse/no-regrets-calendar-2024/
    description:
      "2024 is just around the corner and if there's any resolution to be made, it would be to live your life with no regrets. Whether its planning a vacation, learning a new skill, trying a different activity or signing up for an adventure of a lifetime—do it this year. And what better way to visualize the year than to do it in Miro.",
    tags: ["No Regrets Calendar 2024"],
  },
  {
    id: "uXjVNaHmZgY=",
    title: "A Halloween Quiz",
    url: "https://miro.pxf.io/ZQZBbg",
    description:
      "This fun board has about 66 questions and each question has 4 options one of which is the correct answer. To reveal the correct answer, just pull up the answer card that's sitting behind it.",
    tags: [
      "Halloween Quiz",
      "Miro template",
      "Halloween trivia",
      "quiz game",
      "team building",
      "interactive quiz",
      "virtual activity",
      "team engagement",
      "fun questions",
      "group activity",
      "digital quiz",
      "spooky quiz",
      "team exercise",
      "online trivia",
      "icebreaker game",
      "Halloween fun",
      "quiz categories",
      "team collaboration",
      "meeting icebreaker",
      "Halloween celebration",
    ],
  },
  {
    id: "uXjVNcti5_Q=",
    title: "What's your spooky name?",
    url: "https://miro.pxf.io/1rmRex",
    description:
      "In this halloween themed icebreaker, get your participants to create their own spooky name.",
    tags: [
      "Your Spooky Name",
      "Miro template",
      "Halloween activity",
      "spooky names",
      "team building",
      "fun icebreaker",
      "Halloween game",
      "interactive template",
      "virtual activity",
      "team engagement",
      "creative names",
      "group activity",
      "Halloween fun",
      "name generator",
      "team exercise",
      "Halloween celebration",
      "digital activity",
      "team collaboration",
      "spooky fun",
      "workshop icebreaker",
    ],
  },
  {
    id: "uXjVM0r32bk=",
    title: "A Wooly Retro",
    url: "https://miro.pxf.io/eK6gnr",
    // https://miro.com/miroverse/a-wooly-retro/
    description:
      "Have a ba-aa-ll during this sprint ritual with A Wooly Retro 🐑",
    tags: ["A Wooly Retro"],
  },
  {
    id: "uXjVPS_hTlU=",
    title: "Retro on Mars",
    url: "https://miro.pxf.io/m57ZOq",
    //https://miro.com/miroverse/retro-on-mars/
    description:
      "Will humans travel to Mars in the near future? Maybe. Until that happens, we can still very quickly (and virtually) visit Mars for a retrospective with our entire team. Let's get started!",
    tags: ["Retro on Mars"],
  },
  {
    id: "uXjVPW5Mqds=",
    title: "Retro in the UK",
    url: "https://miro.pxf.io/k0mZ0n",
    // https://miro.com/miroverse/retro-in-the-uk/
    description:
      "For this retrospective, travel with your team to the UK. This retro is divided into four parts. Ready? Let's go!",
    tags: ["Retro in the UK"],
  },
  {
    id: "uXjVOb1cjvU=",
    title: "Retrospective: Aliens",
    url: "https://miro.pxf.io/jrvZW6",
    // https://miro.com/miroverse/retrospective-aliens-ztxqtqwsdk0hj0th/
    description:
      "We've been fantasizing about aliens 👽 for so long that they've now come back to visit us at the end of our sprint. Are you excited about their visit?",
    tags: ["Retrospective: Aliens"],
  },
  {
    id: "uXjVMl28Gao=",
    title: "Effort Reward Matrix",
    url: "https://miro.pxf.io/1rmR5a",
    // https://miro.com/miroverse/effort-reward-template/
    description:
      "Everything rewarding requires some amount of effort. However, the amount of effort is not always proportionately equal to the reward. So, it's a good idea to visualize the effort-to-reward matrix so better decisions can be made.",
    tags: ["Effort Reward Matrix"],
  },
  {
    id: "uXjVMq1DORw=",
    title: "Making Decisions",
    url: "https://miro.pxf.io/5gVYb9",
    // https://miro.com/miroverse/making-decisions/
    description:
      "In a Zakir Khan interview, he shared that while making a decision, he uses three deciding factors — Will I earn something? Will I learn something? Will I meet new people? — and if one-and-a-half out of three satisfies, then he makes the decision in favor.",
    tags: ["Making Decisions"],
  },
  {
    id: "uXjVMpXyJ3o=",
    title: "Hero Themed Profile Cards",
    url: "https://miro.pxf.io/R5kmGa",
    // https://miro.com/miroverse/hero-themed-profile-cards/
    description:
      "Are you looking for fun 'get to know me' profile cards for your next meeting? Here's hero-themed profile cards that you can edit to suit your requirements.",
    tags: ["Hero Themed Profile Cards"],
  },
  {
    id: "uXjVO619vVs=",
    title: "Personal Development: Flight to Success",
    url: "https://miro.pxf.io/XYVOm4",
    // https://miro.com/miroverse/personal-development-flight-to-success/
    description:
      "Focusing on your career and personal development is super important. Use this template to visualize the top 4 career goals and what items you might want to check off to complete each goal. ",
    tags: ["Personal Development: Flight to Success"],
  },
  {
    id: "uXjVMpl7-0k=",
    title: "Resting Up",
    url: "https://miro.pxf.io/LXQ4KL",
    //https://miro.com/miroverse/resting-up/
    description:
      "Use this Miro retrospective board to dive into a rest-themed retro.",
    tags: ["Resting Up"],
  },
  {
    id: "uXjVMw2ffU8=",
    title: "What Would They Do? Your Personal Workbook",
    url: "https://miro.pxf.io/VmGBxa",
    //https://miro.com/miroverse/what-would-they-do-your-personal/
    description:
      "When one is new to the industry, fresh out of Uni, everything can feel quite overwhelming. In some situations, one might even not know what to do, or even how to present themselves. This is when having a framework can really help your career growth. A framework for leveling up in your career.",
    tags: ["What Would They Do? Your Personal Workbook"],
  },
  {
    id: "uXjVMyWBK04=",
    title: "AI Tell Me a Story Jigsaw Puzzle",
    url: "https://miro.pxf.io/Jzx4Kr",
    // https://miro.com/miroverse/ai-tell-me-a-story-jigsaw-puzzle/
    description:
      "In this Miro board, we'll play around with a book-themed jigsaw puzzle and see if we can put it together. The puzzle space is on the left and the reference image is on the right.",
    tags: ["AI Tell Me a Story Jigsaw Puzzle"],
  },
  {
    id: "uXjVPELXwAw=",
    title: "Secret Santa",
    url: "https://miro.pxf.io/Nkr4Kb",
    // https://miro.com/miroverse/secret-santa/
    description:
      "With Miro, we can continue the tradition of Secret Santa and leave virtual presents for one another under the Christmas tree.",
    tags: ["Secret Santa"],
  },
  {
    id: "uXjVMPm7QnM=",
    title: "Eye to Eye Retrospective",
    url: "https://miro.pxf.io/damnOq",
    //https://miro.com/miroverse/eye-to-eye-retrospective/
    description:
      "Retrospective is a time to reflect on the eyes and lows. Bring out your clear lenses and let's see things differently with this retrospective template. ",
    tags: ["Eye to Eye Retrospective"],
  },
  {
    id: "uXjVMJf_TrA=",
    title: "Memories Scrapboard",
    url: "https://miro.pxf.io/q47Zzj",
    //https://miro.com/miroverse/memories-scrapboard/
    description:
      "This is a scrapboard. Instead of writing your messages and sticking pictures in a book of blank pages, you'll put all of that in this Memories Scrapboard.",
    tags: ["Memories Scrapboard"],
  },
  {
    id: "o9J_l6Ot8hk=",
    title: "Hand-Drawn Lean Canvas",
    url: "https://miro.pxf.io/9gXOL0",
    // https://miro.com/miroverse/hand-drawn-lean-canvas/
    description:
      "Lean Canvas is a 1-page business plan template created by Ash Maurya that helps you deconstruct your idea into its key assumptions, now on Miro.",
    tags: ["Hand-Drawn Lean Canvas"],
  },
];
