// https://miro.com/app/?copyBoardId=uXjVKTtrd2w=&isMiroverseTemplate=true
// https://miro.com/app/?copyBoardId=uXjVKTtrd2w%3D&copyTemplateMetaId=5cd000ad-c3e8-45de-aa66-d347ef1e0c2a&isMiroverseTemplate=true

export const MIRO_TEMPLATES = [
  {
    id: "uXjVKTtrd2w=",
    title: "Gratitude Journal",
    url: "https://miro.pxf.io/1r4gxD",
    description: "Start giving thanks and keeping a gratitude journal in Miro.",
    tags: [
      "Gratitude Journal",
      "Miro template",
      "daily gratitude",
      "mindfulness journal",
      "gratitude exercise",
      "personal reflection",
      "daily journaling",
      "mental health template",
      "gratitude practice",
      "well-being journal",
      "reflection journal",
      "journaling template",
      "digital journal",
      "gratitude doodles",
      "daily reflection",
      "Miro journaling",
      "mental health practice",
      "emotional well-being",
      "daily mindfulness",
      "printable journal template",
    ],
  },
  {
    id: "uXjVKOwaHhU=",
    title: "A Hive-ly Retrospective!",
    url: "https://miro.pxf.io/B04GqL",
    description:
      "Commemorate World Bee Day with this retrospective board, adorned with bee-themed decorations serving as a hive of reflection.",
    tags: [
      "Hively Retrospective",
      "Miro template",
      "retrospective board",
      "bee-themed retrospective",
      "team reflection",
      "agile retrospective",
      "team success",
      "lesson sharing",
      "post-it notes",
      "buzzkill moments",
      "team collaboration",
      "innovation reflection",
      "World Bee Day",
      "team achievements",
      "future planning",
      "agile workflows",
      "team workshops",
      "digital retrospective",
      "reflection exercise",
      "Miro retrospective",
    ],
  },
  {
    id: "uXjVKOxk2Ak=",
    title: "Star Wars Puzzle Time",
    url: "https://miro.pxf.io/NkrKMN",
    description:
      "Embark on an epic journey through the galaxy with these Star Wars-themed jigsaw puzzles! 4 puzzles to mark the fourth! ",
    tags: [
      "Star Wars Puzzle",
      "Miro template",
      "Star Wars jigsaw",
      "galaxy puzzle",
      "movie poster puzzle",
      "Star Wars characters",
      "puzzle adventure",
      "May the Fourth Be With You",
      "jigsaw challenge",
      "fun puzzle",
      "Star Wars themed",
      "puzzle journey",
      "interactive puzzle",
      "team building",
      "icebreaker game",
      "puzzle game",
      "digital puzzle",
      "movie puzzle",
      "Star Wars saga",
      "puzzle time",
    ],
  },
  {
    id: "o9J_lHSC6A0=",
    title: "The 4-Step Retrospective",
    url: "https://miro.pxf.io/PyP0Mq",
    description:
      "The 4-step retrospective board is intended to quickly add a simple retrospective template for your retro sessions. ",
    tags: [
      "4-Step Retrospective",
      "Miro template",
      "team reflection",
      "agile retrospective",
      "sprint review",
      "team collaboration",
      "appreciate others",
      "what went well",
      "what can we do better",
      "actions for next sprint",
      "retrospective board",
      "sprint planning",
      "team feedback",
      "digital retrospective",
      "simple retrospective",
      "team achievements",
      "reflect and celebrate",
      "actionable items",
      "team workshops",
      "team success",
    ],
  },
  {
    id: "uXjVKVRJS1w=",
    title: "Circular Conundrums: Easy Maze Marvels",
    url: "https://miro.pxf.io/q47naq",
    description:
      "Side step into the land of Maze Marvels but only this time, we're dealing with circular mazes in Miro.",
    tags: [
      "Circular Conundrums",
      "Easy Maze Marvels",
      "Miro template",
      "circular mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKVWEo3w=",
    title: "Hexa-Maze Magic: Easy Maze Escapades",
    url: "https://miro.pxf.io/Qy5OM9",
    description:
      "Side step into the land of Maze Marvels but only this time, we're dealing with hexagonal mazes in Miro.",
    tags: [
      "Hexa-Maze Magic",
      "Easy Maze Escapades",
      "Miro template",
      "hexagonal mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKWQkBQY=",
    title: "Maze Marvels: Navigate the Challenge!",
    url: "https://miro.pxf.io/ZQZdM0",
    description:
      "The next step of Maze Marvels — Navigate the Challenge — is slightly intermediate-level maze puzzles.",
    tags: [
      "Maze Marvels",
      "Navigate the Challenge",
      "Miro template",
      "intermediate mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKWQUzKI=",
    title: "Maze Marvels: Dare to Navigate the Depths!",
    url: "https://miro.pxf.io/0ZeJVY",
    description:
      "The next step of Maze Marvels — Dare to Navigate the Depths — is hard-level maze puzzles.",
    tags: [
      "Maze Marvels",
      "Navigate the Depths",
      "Miro template",
      "hard-level mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKWQriEQ=",
    title: "Maze Marvels: Fun and Simple Paths to Solve!",
    url: "https://miro.pxf.io/eK64L6",
    description:
      "This is the first of Maze Marvels — an easy introduction to maze puzzles on Miro",
    tags: [
      "Maze Marvels",
      "Fun Simple Paths",
      "Miro template",
      "easy mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKXpy5ok=",
    title: "The Achievable Mountain",
    url: "https://miro.pxf.io/Mm9X7Y",
    description:
      "Visualize your goals in three categories — safe and achievable, ambitious but achievable, and ambitious and far-fetched — to help you pinpoint where to direct your focus.",
    tags: [
      "Achievable Mountain",
      "goal setting",
      "Miro template",
      "visualize goals",
      "safe and achievable goals",
      "ambitious goals",
      "far-fetched goals",
      "goal categories",
      "focus direction",
      "motivational template",
      "personal development",
      "goal planning",
      "success visualization",
      "team goals",
      "effective goal setting",
      "digital goals",
      "productivity template",
      "goal tracking",
      "Miro goal template",
      "achievement strategy",
    ],
  },
  {
    id: "uXjVKZRh5Ks=",
    title: "International Museum Day",
    url: "https://miro.pxf.io/m57gYy",
    description:
      "This International Museum Day, run a fun icebreaker activity in this virtual museum! Enter the museum and open the inside door, as marked, to reveal the icebreaker question.",
    tags: [
      "International Museum Day",
      "Miro template",
      "virtual museum",
      "icebreaker activity",
      "museum lobby",
      "team participation",
      "hidden prompts",
      "museum-themed activity",
      "team building",
      "interactive museum",
      "digital museum",
      "fun icebreaker",
      "group activity",
      "team exercise",
      "virtual team building",
      "museum day event",
      "museum questions",
      "virtual event",
      "team engagement",
      "creative icebreaker",
    ],
  },
  {
    id: "uXjVNrjt7Vo=",
    title: "Easter Egg Prompts",
    url: "https://miro.pxf.io/GmvVA9",
    description:
      "Easter eggs are falling Answer the prompts behind the eggs Before the Easter Bunny gets it all in the basket.",
    tags: [
      "Easter Egg Prompts",
      "Miro template",
      "Easter-themed activity",
      "icebreaker game",
      "team building",
      "interactive prompts",
      "Easter eggs",
      "virtual team activity",
      "digital icebreaker",
      "team engagement",
      "fun prompts",
      "Easter game",
      "team exercise",
      "online activity",
      "group activity",
      "Easter bunny",
      "virtual room",
      "team collaboration",
      "creative icebreaker",
      "Easter event",
    ],
  },
  {
    id: "uXjVNni08_U=",
    title: "Earth Day: Where Do I Go?",
    url: "https://miro.pxf.io/xk750R",
    description:
      "Let's come together to make a positive impact by playing Where Do I Go? In this engaging game, participants collaborate to segregate online images of various types of rubbish into colorful virtual bins.",
    tags: [
      "Earth Day",
      "Where Do I Go",
      "Miro template",
      "eco-friendly activity",
      "Earth Day game",
      "waste management",
      "recycling awareness",
      "virtual icebreaker",
      "team building",
      "environmental education",
      "digital bins",
      "interactive game",
      "team engagement",
      "sustainability activity",
      "Earth Day celebration",
      "green planet",
      "waste segregation",
      "eco-conscious activity",
      "virtual event",
      "group activity",
    ],
  },
  {
    id: "uXjVNr8oVgE=",
    title: "Eco-Friendly Meter",
    url: "https://miro.pxf.io/jrvyM6",
    description:
      "In this Earth Day-based activity, let's find out how eco-friendly of a team you are. 🌍",
    tags: [
      "Eco-Friendly Meter",
      "Miro template",
      "eco-friendly activity",
      "team engagement",
      "environmental awareness",
      "digital meter",
      "sticky notes",
      "team collaboration",
      "going green",
      "eco-conscious",
      "Earth Day activity",
      "virtual activity",
      "interactive meter",
      "sustainability effort",
      "team building",
      "green initiatives",
      "environmental impact",
      "eco-friendly goals",
      "digital board",
      "team exercise",
    ],
  },
  {
    id: "uXjVNplaIYs=",
    title: "Color Me Green and Blue",
    url: "https://miro.pxf.io/k0mM73",
    description:
      "This Earth Day, let's celebrate the beauty of our planet by collectively adding a burst of color to it! Imagine covering the Earth with vibrant green and blue sticky notes, each carrying a positive and uplifting message for the future.",
    tags: [
      "Color Me Green and Blue",
      "Miro template",
      "Earth Day activity",
      "team engagement",
      "environmental awareness",
      "digital sticky notes",
      "interactive exercise",
      "positive messages",
      "nature reflection",
      "team building",
      "green and blue colors",
      "virtual activity",
      "sustainability messages",
      "team collaboration",
      "Earth Day celebration",
      "environmental unity",
      "digital board",
      "team exercise",
      "hopeful messages",
      "planet protection",
    ],
  },
  {
    id: "uXjVNrsfXbQ=",
    title: "Know Your Trees",
    url: "https://miro.pxf.io/eK6EOQ",
    description:
      "There are about 73,300 species of trees on Earth — and each plays an important role in helping humanity thrive. Let's play a game to get to know our trees more.",
    tags: [
      "Know Your Trees",
      "Miro template",
      "tree identification",
      "tree conservation",
      "nature game",
      "interactive learning",
      "tree species",
      "conservation status",
      "environmental education",
      "team activity",
      "tree guessing game",
      "connect the dots",
      "forest biodiversity",
      "digital learning",
      "group activity",
      "team building",
      "ecology education",
      "nature awareness",
      "environmental game",
      "tree knowledge",
    ],
  },
  {
    id: "uXjVN-Ly_bs=",
    title: "Riddle Me This",
    url: "https://miro.pxf.io/LXQ4ao",
    description:
      "This Miro board comes with a bunch of riddles to keep your mind busy. As a facilitator, you can use this board as an icebreaker activity with any type of meeting or even just as a standalone activity.",
    tags: [
      "Riddle Me This",
      "Miro template",
      "riddle game",
      "icebreaker activity",
      "team building",
      "interactive riddles",
      "virtual game",
      "team engagement",
      "brain teasers",
      "fun riddles",
      "group activity",
      "mind challenge",
      "digital icebreaker",
      "puzzle game",
      "team exercise",
      "creative thinking",
      "problem-solving",
      "team collaboration",
      "meeting icebreaker",
      "virtual team activity",
    ],
  },
  {
    id: "uXjVNBp_G8o=",
    title: "Mirocooked Icebreaker",
    url: "https://miro.pxf.io/EK3J0P",
    // https://miro.com/miroverse/mirocooked-icebreaker-template/
    description:
      "Your challenge for today is to help these two chefs in the kitchen and put together a delicious pizza for our guests. ",
    tags: ["Mirocooked Icebreaker"],
  },
  {
    id: "o9J_lqtgU9c=",
    title: "Bulls Eye Feedback",
    url: "https://miro.pxf.io/9gXOVW",
    // https://miro.com/miroverse/bulls-eye-feedback/
    description:
      "Include Bulls Eye Feedback in any of your existing workshop Miro boards to get your team's feedback on your workshop by asking them to place one of the custom made darts anywhere in the target.",
    tags: ["Bulls Eye Feedback"],
  },
  {
    id: "uXjVNENHsLg=",
    title: "What's Your Cupid Name?",
    url: "https://miro.pxf.io/21AMRz",
    // https://miro.com/miroverse/whats-your-cupid-name-template/
    description:
      "In this Valentine's Day-themed icebreaker, get your participants to create their cupid name. You do this by combining a sweet adjective corresponding to the first letter of your name with a cute romantic nickname corresponding to the month you were born.",
    tags: ["What's Your Cupid Name?"],
  },
  {
    id: "uXjVPNKBYEU=",
    title: "A Halloween Retro",
    url: "https://miro.pxf.io/DK2Vvq",
    description:
      "October is Halloween month and if you're hosting a retrospective during this time, how can you even resist a Halloween-themed retro board?",
    tags: [
      "Halloween Retrospective",
      "Miro template",
      "Halloween-themed retro",
      "team reflection",
      "retrospective board",
      "agile retrospective",
      "Halloween bingo",
      "sprint review",
      "team collaboration",
      "spooky retrospective",
      "team achievements",
      "retrospective activities",
      "digital retrospective",
      "team feedback",
      "candy jar kudos",
      "sprint planning",
      "icebreaker game",
      "pumpkin spice latte",
      "retro board",
      "Halloween fun",
    ],
  },
  {
    id: "uXjVNEKNxnE=",
    title: "Cupid Swipe Retro",
    url: "https://miro.pxf.io/y279ZV",
    //https://miro.com/miroverse/cupid-swipe-retro-template/
    description:
      "This Valentine's Day, indulge in a dating app-themed retrospective board. 💖",
    tags: ["Cupid Swipe Retro"],
  },
  {
    id: "uXjVNGV8jhE=",
    title: "Love It or Hate It? Cupid Swipe Icebreaker",
    url: "https://miro.pxf.io/9gXOeW",
    // https://miro.com/miroverse/love-hate-cupid-swipe-icebreaker-template/
    description:
      "A dating app-style icebreaker to get to know what your participants like and dislike and to get the conversations started. Use this in February as a Valentine's Day icebreaker or just any other time of the year for some giggles. ",
    tags: ["Love It or Hate It? Cupid Swipe Icebreaker"],
  },
  {
    id: "uXjVNE24j1g=",
    title: "A Sense of Appreciation",
    url: "https://miro.pxf.io/m57Z4e",
    // https://miro.com/miroverse/sense-of-appreciation-template/
    description:
      "With the help of some Japanese concepts, let's learn to appreciate the different aspects of life in this self-reflection board.",
    tags: ["A Sense of Appreciation"],
  },
  {
    id: "uXjVNIeY7hc=",
    title: "Lean Coffee Cafe",
    url: "https://miro.pxf.io/VmGB4A",
    //https://miro.com/miroverse/lean-coffee-cafe-template/
    description:
      "Welcome to the Lean Coffee Cafe! Today, we have a caffeine-infused three-course menu — we start with items to discuss, then we'll proceed to items we're currently discussing, and finally, items that we've discussed. ☕",
    tags: ["Lean Coffee Cafe"],
  },
  {
    id: "uXjVO4yVWAI=",
    title: "Space Bingo",
    url: "https://miro.pxf.io/an02Ro",
    description:
      "Enjoy a game of Space Bingo as an icebreaker for your next workshop. ",
    tags: [
      "Space Bingo",
      "Miro template",
      "icebreaker game",
      "team building",
      "virtual activity",
      "space-themed game",
      "interactive bingo",
      "dice game",
      "team engagement",
      "fun icebreaker",
      "group activity",
      "digital game",
      "team exercise",
      "online game",
      "workshop icebreaker",
      "creative icebreaker",
      "team collaboration",
      "game instructions",
      "team fun",
      "virtual team activity",
    ],
  },
  {
    id: "uXjVPaTpglg=",
    title: "Gather Town Retrospective",
    url: "https://miro.pxf.io/DK2n0a",
    description:
      "Gather Town tries to make virtual interactions more human by providing a digital space where user avatars can walk around and seamlessly interact with other humans.",
    tags: [
      "Gather Town Retrospective",
      "Miro template",
      "team reflection",
      "virtual retrospective",
      "avatar selection",
      "icebreaker activity",
      "team building",
      "what went well",
      "post-it notes",
      "team kudos",
      "what didn't go well",
      "action items",
      "next sprint planning",
      "unwind at the park",
      "digital retrospective",
      "team collaboration",
      "agile workflows",
      "interactive retrospective",
      "team exercise",
      "virtual team activity",
    ],
  },
  {
    id: "uXjVNHSP1OQ=",
    title: "Frosty Firestarter's",
    url: "https://miro.pxf.io/ZQZBrq",
    // https://miro.com/miroverse/frosty-firestarters/
    description:
      "Thanks for cloning this Frosty Firestarter's template. This is a simple icebreaker template which contains heaps of dragon-themed prompt cards in the center of the deck. 🐉",
    tags: ["Frosty Firestarter's"],
  },
  {
    id: "uXjVNJA2FJo=",
    title: "Hang Those Christmas Stockings",
    url: "https://miro.pxf.io/oq70nb",
    //https://miro.com/miroverse/hang-those-christmas-stockings-template/
    description:
      "Let's keep the Christmas stocking tradition alive virtually using this simple Miro board. Wondering how? Follow along! 🎄🎅🧦",
    tags: ["Hang Those Christmas Stockings"],
  },
  {
    id: "o9J_lCs6DkM=",
    title: "Retrospective in the Island of Golocans",
    url: "https://miro.pxf.io/xk1NMk",
    // https://miro.com/miroverse/retrospective-in-the-island-of-golocans/
    description:
      "When performing a retrospective on the Island of Golocans, remember to cover all four directions. Have a pleasant time exploring this island!",
    tags: [
      "Retrospective in the Island of Golocans",
      "featured template",
      "award winning",
      "one piece",
    ],
  },
  {
    id: "uXjVNS0uLGQ=",
    title: "Would You Rather? Shopping Edition",
    url: "https://miro.pxf.io/q47Z4j",
    // https://miro.com/miroverse/would-you-rather-shopping-edition-template/
    description:
      "To play a game of 'Would You Rather,' gather a group of participants and take turns presenting each other with a choice between two hypothetical options, often amusing, creating interesting dilemmas. Participants must choose a side using and might also go about explaining their choice if they'd like.",
    tags: ["Would You Rather? Shopping Edition"],
  },
  {
    id: "uXjVNTaX6tw=",
    title: "Black Friday Bingo Cards",
    url: "https://miro.pxf.io/zN7rxe",
    //https://miro.com/miroverse/black-friday-bingo-cards-template/
    description:
      "To play, choose a bingo card set and then ask each other if you've ever had these shopping experiences. Each person gets a card from the selected set. If you have had the shopping experience, mark the square with the marker provided.",
    tags: ["Black Friday Bingo Cards"],
  },
  {
    id: "o9J_l9J6AHY=",
    title: "The Writing Process",
    url: "https://miro.pxf.io/rQ7OQ5",
    // https://miro.com/miroverse/the-writing-process/
    description:
      "The writing process can be overwhelming at times. But it doesn't always have to be. To make your life smooth, I've created this all-in-one template that you can copy and fill up.",
    tags: ["The Writing Process"],
  },
  {
    id: "uXjVNSuta38=",
    title: "Word Search Shopping Edition",
    url: "https://miro.pxf.io/rQ7On5",
    // https://miro.com/miroverse/word-search-shopping-edition-template/
    description:
      "Locate below listed words hidden within this grid of letters. These words can be arranged horizontally, vertically, or diagonally, in any direction.",
    tags: ["Word Search Shopping Edition"],
  },
  {
    id: "uXjVNT6LVfA=",
    title: "No Regrets Calendar 2024",
    url: "https://miro.pxf.io/EK3JEe",
    //https://miro.com/miroverse/no-regrets-calendar-2024/
    description:
      "2024 is just around the corner and if there's any resolution to be made, it would be to live your life with no regrets. Whether its planning a vacation, learning a new skill, trying a different activity or signing up for an adventure of a lifetime—do it this year. And what better way to visualize the year than to do it in Miro.",
    tags: ["No Regrets Calendar 2024"],
  },
  {
    id: "uXjVNaHmZgY=",
    title: "A Halloween Quiz",
    url: "https://miro.pxf.io/ZQZBbg",
    description:
      "This fun board has about 66 questions and each question has 4 options one of which is the correct answer. To reveal the correct answer, just pull up the answer card that's sitting behind it.",
    tags: [
      "Halloween Quiz",
      "Miro template",
      "Halloween trivia",
      "quiz game",
      "team building",
      "interactive quiz",
      "virtual activity",
      "team engagement",
      "fun questions",
      "group activity",
      "digital quiz",
      "spooky quiz",
      "team exercise",
      "online trivia",
      "icebreaker game",
      "Halloween fun",
      "quiz categories",
      "team collaboration",
      "meeting icebreaker",
      "Halloween celebration",
    ],
  },
  {
    id: "uXjVNcti5_Q=",
    title: "What's your spooky name?",
    url: "https://miro.pxf.io/1rmRex",
    description:
      "In this halloween themed icebreaker, get your participants to create their own spooky name.",
    tags: [
      "Your Spooky Name",
      "Miro template",
      "Halloween activity",
      "spooky names",
      "team building",
      "fun icebreaker",
      "Halloween game",
      "interactive template",
      "virtual activity",
      "team engagement",
      "creative names",
      "group activity",
      "Halloween fun",
      "name generator",
      "team exercise",
      "Halloween celebration",
      "digital activity",
      "team collaboration",
      "spooky fun",
      "workshop icebreaker",
    ],
  },
  {
    id: "uXjVM0r32bk=",
    title: "A Wooly Retro",
    url: "https://miro.pxf.io/eK6gnr",
    // https://miro.com/miroverse/a-wooly-retro/
    description:
      "Have a ba-aa-ll during this sprint ritual with A Wooly Retro 🐑",
    tags: ["A Wooly Retro"],
  },
  {
    id: "uXjVPS_hTlU=",
    title: "Retro on Mars",
    url: "https://miro.pxf.io/m57ZOq",
    //https://miro.com/miroverse/retro-on-mars/
    description:
      "Will humans travel to Mars in the near future? Maybe. Until that happens, we can still very quickly (and virtually) visit Mars for a retrospective with our entire team. Let's get started!",
    tags: ["Retro on Mars"],
  },
  {
    id: "uXjVPW5Mqds=",
    title: "Retro in the UK",
    url: "https://miro.pxf.io/k0mZ0n",
    // https://miro.com/miroverse/retro-in-the-uk/
    description:
      "For this retrospective, travel with your team to the UK. This retro is divided into four parts. Ready? Let's go!",
    tags: ["Retro in the UK"],
  },
  {
    id: "uXjVOb1cjvU=",
    title: "Retrospective: Aliens",
    url: "https://miro.pxf.io/jrvZW6",
    // https://miro.com/miroverse/retrospective-aliens-ztxqtqwsdk0hj0th/
    description:
      "We've been fantasizing about aliens 👽 for so long that they've now come back to visit us at the end of our sprint. Are you excited about their visit?",
    tags: ["Retrospective: Aliens"],
  },
  {
    id: "uXjVMl28Gao=",
    title: "Effort Reward Matrix",
    url: "https://miro.pxf.io/1rmR5a",
    // https://miro.com/miroverse/effort-reward-template/
    description:
      "Everything rewarding requires some amount of effort. However, the amount of effort is not always proportionately equal to the reward. So, it's a good idea to visualize the effort-to-reward matrix so better decisions can be made.",
    tags: ["Effort Reward Matrix"],
  },
  {
    id: "uXjVMq1DORw=",
    title: "Making Decisions",
    url: "https://miro.pxf.io/5gVYb9",
    // https://miro.com/miroverse/making-decisions/
    description:
      "In a Zakir Khan interview, he shared that while making a decision, he uses three deciding factors — Will I earn something? Will I learn something? Will I meet new people? — and if one-and-a-half out of three satisfies, then he makes the decision in favor.",
    tags: ["Making Decisions"],
  },
  {
    id: "uXjVMpXyJ3o=",
    title: "Hero Themed Profile Cards",
    url: "https://miro.pxf.io/R5kmGa",
    // https://miro.com/miroverse/hero-themed-profile-cards/
    description:
      "Are you looking for fun 'get to know me' profile cards for your next meeting? Here's hero-themed profile cards that you can edit to suit your requirements.",
    tags: ["Hero Themed Profile Cards"],
  },
  {
    id: "uXjVO619vVs=",
    title: "Personal Development: Flight to Success",
    url: "https://miro.pxf.io/XYVOm4",
    // https://miro.com/miroverse/personal-development-flight-to-success/
    description:
      "Focusing on your career and personal development is super important. Use this template to visualize the top 4 career goals and what items you might want to check off to complete each goal. ",
    tags: ["Personal Development: Flight to Success"],
  },
  {
    id: "uXjVMpl7-0k=",
    title: "Resting Up",
    url: "https://miro.pxf.io/LXQ4KL",
    //https://miro.com/miroverse/resting-up/
    description:
      "Use this Miro retrospective board to dive into a rest-themed retro.",
    tags: ["Resting Up"],
  },
  {
    id: "uXjVMw2ffU8=",
    title: "What Would They Do? Your Personal Workbook",
    url: "https://miro.pxf.io/VmGBxa",
    //https://miro.com/miroverse/what-would-they-do-your-personal/
    description:
      "When one is new to the industry, fresh out of Uni, everything can feel quite overwhelming. In some situations, one might even not know what to do, or even how to present themselves. This is when having a framework can really help your career growth. A framework for leveling up in your career.",
    tags: ["What Would They Do? Your Personal Workbook"],
  },
  {
    id: "uXjVMyWBK04=",
    title: "AI Tell Me a Story Jigsaw Puzzle",
    url: "https://miro.pxf.io/Jzx4Kr",
    // https://miro.com/miroverse/ai-tell-me-a-story-jigsaw-puzzle/
    description:
      "In this Miro board, we'll play around with a book-themed jigsaw puzzle and see if we can put it together. The puzzle space is on the left and the reference image is on the right.",
    tags: ["AI Tell Me a Story Jigsaw Puzzle"],
  },
  {
    id: "uXjVPELXwAw=",
    title: "Secret Santa",
    url: "https://miro.pxf.io/Nkr4Kb",
    // https://miro.com/miroverse/secret-santa/
    description:
      "With Miro, we can continue the tradition of Secret Santa and leave virtual presents for one another under the Christmas tree.",
    tags: ["Secret Santa"],
  },
  {
    id: "uXjVMPm7QnM=",
    title: "Eye to Eye Retrospective",
    url: "https://miro.pxf.io/damnOq",
    //https://miro.com/miroverse/eye-to-eye-retrospective/
    description:
      "Retrospective is a time to reflect on the eyes and lows. Bring out your clear lenses and let's see things differently with this retrospective template. ",
    tags: ["Eye to Eye Retrospective"],
  },
  {
    id: "uXjVMJf_TrA=",
    title: "Memories Scrapboard",
    url: "https://miro.pxf.io/q47Zzj",
    //https://miro.com/miroverse/memories-scrapboard/
    description:
      "This is a scrapboard. Instead of writing your messages and sticking pictures in a book of blank pages, you'll put all of that in this Memories Scrapboard.",
    tags: ["Memories Scrapboard"],
  },
  {
    id: "o9J_l6Ot8hk=",
    title: "Hand-Drawn Lean Canvas",
    url: "https://miro.pxf.io/9gXOL0",
    // https://miro.com/miroverse/hand-drawn-lean-canvas/
    description:
      "Lean Canvas is a 1-page business plan template created by Ash Maurya that helps you deconstruct your idea into its key assumptions, now on Miro.",
    tags: ["Hand-Drawn Lean Canvas"],
  },
];
