export const MIRO_TEMPLATES = [
  {
    id: "uXjVKU1RBSs=",
    title: "Gratitude Journal",
    url: "https://miro.pxf.io/1r4gxD",
    description: "some gratitude here",
    tags: [
      "Gratitude Journal",
      "Miro template",
      "daily gratitude",
      "mindfulness journal",
      "gratitude exercise",
      "personal reflection",
      "daily journaling",
      "mental health template",
      "gratitude practice",
      "well-being journal",
      "reflection journal",
      "journaling template",
      "digital journal",
      "gratitude doodles",
      "daily reflection",
      "Miro journaling",
      "mental health practice",
      "emotional well-being",
      "daily mindfulness",
      "printable journal template",
    ],
  },
  {
    id: "uXjVKOxgOgU=",
    title: "A Hive-ly Retrospective!",
    url: "https://miro.pxf.io/B04GqL",
    description: "hive busssss",
    tags: [
      "Hively Retrospective",
      "Miro template",
      "retrospective board",
      "bee-themed retrospective",
      "team reflection",
      "agile retrospective",
      "team success",
      "lesson sharing",
      "post-it notes",
      "buzzkill moments",
      "team collaboration",
      "innovation reflection",
      "World Bee Day",
      "team achievements",
      "future planning",
      "agile workflows",
      "team workshops",
      "digital retrospective",
      "reflection exercise",
      "Miro retrospective",
    ],
  },
];
