export const MIRO_TEMPLATES = [
  {
    id: "uXjVKU1RBSs=",
    title: "Gratitude Journal",
    url: "https://miro.pxf.io/1r4gxD",
    description: "some gratitude here",
    tags: [
      "Gratitude Journal",
      "Miro template",
      "daily gratitude",
      "mindfulness journal",
      "gratitude exercise",
      "personal reflection",
      "daily journaling",
      "mental health template",
      "gratitude practice",
      "well-being journal",
      "reflection journal",
      "journaling template",
      "digital journal",
      "gratitude doodles",
      "daily reflection",
      "Miro journaling",
      "mental health practice",
      "emotional well-being",
      "daily mindfulness",
      "printable journal template",
    ],
  },
  {
    id: "uXjVKOxgOgU=",
    title: "A Hive-ly Retrospective!",
    url: "https://miro.pxf.io/B04GqL",
    description: "hive busssss",
    tags: [
      "Hively Retrospective",
      "Miro template",
      "retrospective board",
      "bee-themed retrospective",
      "team reflection",
      "agile retrospective",
      "team success",
      "lesson sharing",
      "post-it notes",
      "buzzkill moments",
      "team collaboration",
      "innovation reflection",
      "World Bee Day",
      "team achievements",
      "future planning",
      "agile workflows",
      "team workshops",
      "digital retrospective",
      "reflection exercise",
      "Miro retrospective",
    ],
  },
  {
    id: "uXjVKPdwzCE=",
    title: "Star Wars Puzzle Time",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVKVTYUAQ=",
    title: "Circular Conundrums: Easy Maze Marvels",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVKVXrnGY=",
    title: "Hexa-Maze Magic: Easy Maze Escapades",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVKWQx56U=",
    title: "Maze Marvels: Navigate the Challenge!",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVKWQbejM=",
    title: "Maze Marvels: Dare to Navigate the Depths!",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVKWMyU0I=",
    title: "Maze Marvels: Fun and Simple Paths to Solve!",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVKZSSBaQ=",
    title: "The Achievable Mountain",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNnEkYRI=",
    title: "International Museum Day",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNupFVS8=",
    title: "Easter Egg Prompts",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNop4XzY=",
    title: "Where Do I Go?",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNr8oVgE=",
    title: "Eco-Friendly Meter",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNpmMgL8=",
    title: "Color Me Green and Blue",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNriRb2g=",
    title: "Know Your Trees",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNBpfKJs=",
    title: "Riddle Me This",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNDILe-M=",
    title: "Mirocooked",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNEKEgIA=",
    title: "What's Your Cupid Name?",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNTgr7h8=",
    title: "A Halloween Retro by Clyde D'Souza",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNFbczZ4=",
    title: "Cupid Swipe Retro",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNGzabHU=",
    title: "Love It or Hate It? Cupid Swipe Icebreaker",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNFbczb4=",
    title: "A Sense of Appreciation",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNKrYMyw=",
    title: "Lean Coffee Cafe",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNHxQlg0=",
    title: "Frosty Firestarter's",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNKxg8lE=",
    title: "Hang Those Christmas Stockings",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNSvTGKU=",
    title: "Would You Rather? Shopping Edition",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNTgr6a0=",
    title: "Black Friday Bingo Cards",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNTUDzoM=",
    title: "Word Search Shopping Edition",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNVJS2i0=",
    title: "No Regrets Calendar 2024",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNcLOzdg=",
    title: "A Halloween Quiz",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNcqLWV4=",
    title: "What's your spooky name?",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMoqWE38=",
    title: "A Wooly Retro by Clyde D'Souza",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMnDeJxQ=",
    title: "Effort Reward Matrix",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMqhi8-o=",
    title: "Making Decisions",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMwGA_cg=",
    title: "Profile Cards",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMq2TCkQ=",
    title: "Resting Up",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMx78EJM=",
    title: "What Would They Do? Your Personal Workbook",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMyRSq38=",
    title: "AI Tell Me a Story Jigsaw Puzzle",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMXeDCss=",
    title: "Eye to Eye Retrospective",
    url: "",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMXeDCss=",
    title: "Eye to Eye Retrospective",
    url: "",
    description: "",
    tags: [],
  },
];
