// https://miro.com/app/?copyBoardId=uXjVKTtrd2w=&isMiroverseTemplate=true
// https://miro.com/app/?copyBoardId=uXjVKTtrd2w%3D&copyTemplateMetaId=5cd000ad-c3e8-45de-aa66-d347ef1e0c2a&isMiroverseTemplate=true

export const MIRO_TEMPLATES = [
  {
    id: "uXjVKTtrd2w=",
    title: "Gratitude Journal",
    url: "https://miro.pxf.io/1r4gxD",
    description: "Start giving thanks and keeping a gratitude journal in Miro.",
    tags: [
      "Gratitude Journal",
      "Miro template",
      "daily gratitude",
      "mindfulness journal",
      "gratitude exercise",
      "personal reflection",
      "daily journaling",
      "mental health template",
      "gratitude practice",
      "well-being journal",
      "reflection journal",
      "journaling template",
      "digital journal",
      "gratitude doodles",
      "daily reflection",
      "Miro journaling",
      "mental health practice",
      "emotional well-being",
      "daily mindfulness",
      "printable journal template",
    ],
  },
  {
    id: "uXjVKOwaHhU=",
    title: "A Hive-ly Retrospective!",
    url: "https://miro.pxf.io/B04GqL",
    description:
      "Commemorate World Bee Day with this retrospective board, adorned with bee-themed decorations serving as a hive of reflection.",
    tags: [
      "Hively Retrospective",
      "Miro template",
      "retrospective board",
      "bee-themed retrospective",
      "team reflection",
      "agile retrospective",
      "team success",
      "lesson sharing",
      "post-it notes",
      "buzzkill moments",
      "team collaboration",
      "innovation reflection",
      "World Bee Day",
      "team achievements",
      "future planning",
      "agile workflows",
      "team workshops",
      "digital retrospective",
      "reflection exercise",
      "Miro retrospective",
    ],
  },
  {
    id: "uXjVKOxk2Ak=",
    title: "Star Wars Puzzle Time",
    url: "https://miro.pxf.io/NkrKMN",
    description:
      "Embark on an epic journey through the galaxy with these Star Wars-themed jigsaw puzzles! 4 puzzles to mark the fourth! ",
    tags: [
      "Star Wars Puzzle",
      "Miro template",
      "Star Wars jigsaw",
      "galaxy puzzle",
      "movie poster puzzle",
      "Star Wars characters",
      "puzzle adventure",
      "May the Fourth Be With You",
      "jigsaw challenge",
      "fun puzzle",
      "Star Wars themed",
      "puzzle journey",
      "interactive puzzle",
      "team building",
      "icebreaker game",
      "puzzle game",
      "digital puzzle",
      "movie puzzle",
      "Star Wars saga",
      "puzzle time",
    ],
  },
  {
    id: "o9J_lHSC6A0=",
    title: "The 4-Step Retrospective",
    url: "https://miro.pxf.io/PyP0Mq",
    description:
      "The 4-step retrospective board is intended to quickly add a simple retrospective template for your retro sessions. ",
    tags: [
      "4-Step Retrospective",
      "Miro template",
      "team reflection",
      "agile retrospective",
      "sprint review",
      "team collaboration",
      "appreciate others",
      "what went well",
      "what can we do better",
      "actions for next sprint",
      "retrospective board",
      "sprint planning",
      "team feedback",
      "digital retrospective",
      "simple retrospective",
      "team achievements",
      "reflect and celebrate",
      "actionable items",
      "team workshops",
      "team success",
    ],
  },
  {
    id: "uXjVKVRJS1w=",
    title: "Circular Conundrums: Easy Maze Marvels",
    url: "https://miro.pxf.io/q47naq",
    description:
      "Side step into the land of Maze Marvels but only this time, we’re dealing with circular mazes in Miro.",
    tags: [
      "Circular Conundrums",
      "Easy Maze Marvels",
      "Miro template",
      "circular mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKVWEo3w=",
    title: "Hexa-Maze Magic: Easy Maze Escapades",
    url: "https://miro.pxf.io/Qy5OM9",
    description:
      "Side step into the land of Maze Marvels but only this time, we’re dealing with hexagonal mazes in Miro.",
    tags: [
      "Hexa-Maze Magic",
      "Easy Maze Escapades",
      "Miro template",
      "hexagonal mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKWQkBQY=",
    title: "Maze Marvels: Navigate the Challenge!",
    url: "https://miro.pxf.io/ZQZdM0",
    description:
      "The next step of Maze Marvels — Navigate the Challenge — is slightly intermediate-level maze puzzles.",
    tags: [
      "Maze Marvels",
      "Navigate the Challenge",
      "Miro template",
      "intermediate mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKWQUzKI=",
    title: "Maze Marvels: Dare to Navigate the Depths!",
    url: "https://miro.pxf.io/0ZeJVY",
    description:
      "The next step of Maze Marvels — Dare to Navigate the Depths — is hard-level maze puzzles.",
    tags: [
      "Maze Marvels",
      "Navigate the Depths",
      "Miro template",
      "hard-level mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKWQriEQ=",
    title: "Maze Marvels: Fun and Simple Paths to Solve!",
    url: "https://miro.pxf.io/eK64L6",
    description:
      "This is the first of Maze Marvels — an easy introduction to maze puzzles on Miro",
    tags: [
      "Maze Marvels",
      "Fun Simple Paths",
      "Miro template",
      "easy mazes",
      "maze challenge",
      "team activity",
      "interactive maze",
      "digital maze",
      "pen tool",
      "eraser tool",
      "team building",
      "fun maze",
      "collaborative puzzle",
      "problem-solving",
      "maze adventure",
      "puzzle game",
      "maze navigation",
      "online maze",
      "team exercise",
      "group activity",
    ],
  },
  {
    id: "uXjVKXpy5ok=",
    title: "The Achievable Mountain",
    url: "https://miro.pxf.io/Mm9X7Y",
    description:
      "Visualize your goals in three categories — safe and achievable, ambitious but achievable, and ambitious and far-fetched — to help you pinpoint where to direct your focus.",
    tags: [
      "Achievable Mountain",
      "goal setting",
      "Miro template",
      "visualize goals",
      "safe and achievable goals",
      "ambitious goals",
      "far-fetched goals",
      "goal categories",
      "focus direction",
      "motivational template",
      "personal development",
      "goal planning",
      "success visualization",
      "team goals",
      "effective goal setting",
      "digital goals",
      "productivity template",
      "goal tracking",
      "Miro goal template",
      "achievement strategy",
    ],
  },
  {
    id: "uXjVKZRh5Ks=",
    title: "International Museum Day",
    url: "https://miro.pxf.io/m57gYy",
    description:
      "This International Museum Day, run a fun icebreaker activity in this virtual museum! Enter the museum and open the inside door, as marked, to reveal the icebreaker question.",
    tags: [
      "International Museum Day",
      "Miro template",
      "virtual museum",
      "icebreaker activity",
      "museum lobby",
      "team participation",
      "hidden prompts",
      "museum-themed activity",
      "team building",
      "interactive museum",
      "digital museum",
      "fun icebreaker",
      "group activity",
      "team exercise",
      "virtual team building",
      "museum day event",
      "museum questions",
      "virtual event",
      "team engagement",
      "creative icebreaker",
    ],
  },
  //26 july
  {
    id: "uXjVNupFVS8=",
    title: "Easter Egg Prompts",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNop4XzY=",
    title: "Where Do I Go?",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNr8oVgE=",
    title: "Eco-Friendly Meter",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNpmMgL8=",
    title: "Color Me Green and Blue",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNriRb2g=",
    title: "Know Your Trees",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNBpfKJs=",
    title: "Riddle Me This",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNDILe-M=",
    title: "Mirocooked",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNEKEgIA=",
    title: "What's Your Cupid Name?",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVPNKBYEU=",
    title: "A Halloween Retro",
    url: "https://miro.pxf.io/DK2Vvq",
    description:
      "October is Halloween month and if you're hosting a retrospective during this time, how can you even resist a Halloween-themed retro board?",
    tags: [
      "Halloween Retrospective",
      "Miro template",
      "Halloween-themed retro",
      "team reflection",
      "retrospective board",
      "agile retrospective",
      "Halloween bingo",
      "sprint review",
      "team collaboration",
      "spooky retrospective",
      "team achievements",
      "retrospective activities",
      "digital retrospective",
      "team feedback",
      "candy jar kudos",
      "sprint planning",
      "icebreaker game",
      "pumpkin spice latte",
      "retro board",
      "Halloween fun",
    ],
  },
  {
    id: "uXjVNFbczZ4=",
    title: "Cupid Swipe Retro",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNGzabHU=",
    title: "Love It or Hate It? Cupid Swipe Icebreaker",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNFbczb4=",
    title: "A Sense of Appreciation",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNKrYMyw=",
    title: "Lean Coffee Cafe",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNHxQlg0=",
    title: "Frosty Firestarter's",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNKxg8lE=",
    title: "Hang Those Christmas Stockings",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNSvTGKU=",
    title: "Would You Rather? Shopping Edition",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNTgr6a0=",
    title: "Black Friday Bingo Cards",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNTUDzoM=",
    title: "Word Search Shopping Edition",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNVJS2i0=",
    title: "No Regrets Calendar 2024",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNcLOzdg=",
    title: "A Halloween Quiz",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVNcqLWV4=",
    title: "What's your spooky name?",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMoqWE38=",
    title: "A Wooly Retro by Clyde D'Souza",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMnDeJxQ=",
    title: "Effort Reward Matrix",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMqhi8-o=",
    title: "Making Decisions",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMwGA_cg=",
    title: "Profile Cards",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMq2TCkQ=",
    title: "Resting Up",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMx78EJM=",
    title: "What Would They Do? Your Personal Workbook",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMyRSq38=",
    title: "AI Tell Me a Story Jigsaw Puzzle",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMXeDCss=",
    title: "Eye to Eye Retrospective",
    url: "https://",
    description: "",
    tags: [],
  },
  {
    id: "uXjVMXeDCss=",
    title: "Eye to Eye Retrospective",
    url: "https://",
    description: "",
    tags: [],
  },
];
